---
# tasks file for slurm
- name: start time #just to check start
  ansible.legacy.command: bash -c 'echo "$(date +%Y-%m-%d_%H:%M:%S) app start" >> /tmp/ansible.log'

- name: init nginx role from galaxy
  ansible.legacy.shell: bash -c 'ansible-galaxy install nginxinc.nginx'

- name: install packages
  ansible.builtin.yum:
    name: 
      - "@development"
      - libxml2-devel
#      - ruby
#      - ruby-devel
      - gcc
      - make
      - centos-release-scl
      - postgresql-devel 
    state: present
#  when: install_packages|default(false) | bool

- name: install ruby
  ansible.builtin.yum:
    name: 
      - rh-ruby27
      - rh-ruby27-ruby-devel
      - rh-ruby27-rubygems
      - rh-ruby27-rubygem-bundler
    state: present

#- name: install bundler,puma gem
#  ansible.builtin.gem:
#    name: 
#      - bundler
#      - puma
#    state: present

- name: read settings #depr
  ansible.builtin.shell: source "{{ inventory_dir }}"/settings && env
  register: env_output
- name: list settings #depr
  ansible.legacy.copy:
    content: "{{ env_output.stdout }}"
    dest: /tmp/ansible.settings

- name: copy ruby app
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/slurmapp/xpaste_practicum"
    dest: /var/app/
    owner: vagrant
    group: vagrant
    mode: '0755'

- name: make effictive ruby version and install gems
  ansible.builtin.shell: |
      source /opt/rh/rh-ruby27/enable
      gem install bundler:1.6.2
      gem install nokogiri:1.8.2
      gem install rails-dom-testing:2.0.3
  args:
    chdir: /var/app/xpaste_practicum

- name: install all dependencies
  ansible.builtin.shell: |
    source /opt/rh/rh-ruby27/enable
    bundle config build.nokogiri --use-system-libraries
    bundle install
    #bundle install --clean --no-cache --without development
  args: 
    chdir: /var/app/xpaste_practicum
  ignore_errors: yes

 
- name: copy service file
  ansible.builtin.copy:
    src: slurmapp.service
    dest: /etc/systemd/system/slurmapp.service 
    mode: '0644'

- name: run and enable
  ansible.builtin.service:
    name: slurmapp.service
    state: started
    enabled: yes
    daemon_reload: yes
